### ISSUE TITLE
Change organisation name to "Research Intelligence"?

### ISSUE THREAD

**Issue by juancastilla** [Research-Intelligence/Research-Intelligence#3]
@mlcanales

**Comment by mlcanales** [comment]
Changed, remember to change now where repos point to (locally)

**Comment by mlcanales** [comment]
That would be in the terminal: 
Check current urls: `git remote -v`
Change url: `git remote set-url origin https://github.com/Research-Intelligence/Research-Intelligence.git`
Check changes: `git remote -v`
